{{- if .Values.registry.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portfolio.fullname" . }}-registry
  labels:
    app.kubernetes.io/name: {{ include "portfolio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "portfolio.registryAuth" . }}
{{- end }}
