{{- if .Values.registry.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "portfolio.registryAuth" . }}
{{- end }}
